chore: add aspects plugin
overhangio/tpi pull request #4
Opened 2024-11-05 21:36 UTC by Ian2012

This PR adds the aspects plugin to the list of contrib plugins.

2024-11-08 11:02 UTC, regisb requested changes

2024-11-08 12:03 UTC, Ian2012 commented on contrib/redwood/plugins.yml
> +  src: tutor-contrib-aspects==1.2.0
We will have a v1.2.1 release soon and then drop support for python3.8 in multiple places. @bmtcril what do you think the version constraint should be? `<3.0`

2024-11-08 12:06 UTC, Ian2012 commented on contrib/redwood/plugins.yml
> +  src: tutor-contrib-aspects==1.2.0
I can also use <2.0.0 while 2.0.0 is confirmed

2024-11-08 15:07 UTC, bmtcril commented on contrib/redwood/plugins.yml
> +  src: tutor-contrib-aspects==1.2.0
<2 should be good for now. 2.x will be the breaking version.

2024-11-08 15:12 UTC, Ian2012 commented on contrib/redwood/plugins.yml
> +  src: tutor-contrib-aspects==1.2.0
@regisb should I also add a lower bound? `>1.0.0`?

2024-11-11 07:35 UTC, DawoudSheraz approved these changes

2024-11-11 10:49 UTC, regisb commented on contrib/redwood/plugins.yml
> +  src: tutor-contrib-aspects==1.2.0
I have no idea, it's really up to you.

2024-11-11 10:49 UTC, regisb commented on contrib/olive/plugins.yml
> +  maintainer: Brian Messick <bmesick@axim.org>
Messick -> Mesick
(same below)

2024-11-19 11:32 UTC, merged